The Next Energy Generation - Nordic Energy platform´s built on a modern Node.js technology stack — designed for teams who need power, flexibility and performance.

open_collective: Nordic Energy
consepts: https://nordicenergy.io/docs/concepts/contributing/
token sales: https://nordicenergy.io
donate: 
